whatwg/encoding

- Overview.html
- Overview.src.html
Because of deployed content index gb18030 maps 0xA3 0xA0 to U+3000
rather than U+E5E5 when decoding. Therefore encoding U+E5E5 cannot work
either.
> Fix #17: gb18030 cannot encode U+E5E5

- Overview.html
- Overview.src.html
Also remove the replacement encoder which would be weird to use anyway
as the encoding label would be “replacement” rather than “utf-8”.
> Fix #29: introduce output encoding for URL and HTML forms

- Overview.html
- Overview.src.html
This also allows us to remove the UTF-16 encoders as they are not
exposed in any way after TextEncoder support is removed.
> Fix #18: remove UTF-16 support from TextEncoder

- Overview.html
- Overview.src.html
1. Instead of subtracting a magic number, do a bitwise AND to pick a number of least-significant bits that makes sense if you consider the UTF-8 bytes bitwise.
2. Instead of shifting by variable amounts in order to put all bits into their final destination directly, always shift by a constant six and let the higher bits be shifted a number of times.
> Avoid teaching bad UTF-8 math.

- encodings.json
Looks like a find-and-replace oversight.
> Make the name of ISO-8859-8-I all upper case in encodings.json.

- Overview.html
- Overview.src.html
> Handle EUDC before the index in Shift_JIS

- encoding.bs
In EUC-JP and ISO-2022-JP encoders, when getting a pointer for a code
point in index jis0208, it’s important to note that the pointer is
always less than 8836. This is because the code points are duplicated
throughout the table and the index pointer returns the first.
Per a suggestion in #47.
> Note >8835 pointers in index jis0208 cannot be reached

- deploy.sh
- encoding.bs
- visualization-colors.css
- visualization.css
- visualize.py
> Non-normatively visualize the indexes

- encoding.bs
***
[Preview](https://s3.amazonaws.com/pr-preview/aphillips/encoding-1/master.html) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/encoding/f2c6682...aphillips:92c23a9.html)
> Fixes #95: added two rowspan=2 to the 8859-9-i table

- encoding.bs
Fixes #92.
***
[Preview](https://encoding.spec.whatwg.org/branch-snapshots/annevk/avoid-copy/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/encoding/ee2bd34...180c06f.html)
> Encourage implementations to avoid copying in TextDecoder

- encoding.bs
Fixes #66.
***
[Preview](https://encoding.spec.whatwg.org/branch-snapshots/annevk/roof/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/encoding/ee2bd34...7eba85a.html)
> Editorial: remove floor() operation in favor of integer division

- .travis.yml
- deploy.sh
* Switch to using the HTML checker network API rather than `vnu.jar`
* Add a `CHECKER_PARAMS` environment variable to `.travis.yml` to cause the
HTML checker to suppress warnings about Unicode non-NFC text runs and also
about use of Unicode Private Use area, and about missing `html[lang]`
> Use HTML checker network API + suppress warnings

- encoding.bs
See https://github.com/whatwg/encoding/issues/59#issuecomment-297750352
for context.
***
[Preview](https://encoding.spec.whatwg.org/branch-snapshots/annevk/euc-jp-ascii/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/encoding/612f9c6...b3bbc1b.html)
> EUC-JP: only unwind ASCII bytes

- encoding.bs
In particular in all places with two null checks in a row and for
EUC-JP as it would stand out otherwise.
***
[Preview](https://encoding.spec.whatwg.org/branch-snapshots/annevk/null-checks/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/encoding/a85149b...be6ddad.html)
> Editorial: check non-null before null

- encoding.bs
***
[Preview](https://encoding.spec.whatwg.org/branch-snapshots/annevk/substeps/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/encoding/4e53e16...6d4f6e3.html)
> Editorial: remove substeps as a concept

- encoding.bs
Instead of always unwinding if there’s no code point when consuming the
fourth byte, only unwind when the fourth byte is not an ASCII digit.
This does mean that ASCII digits can be masked, but since ASCII digits
are not used as delimiter in any format this is highly unlikely to be
used in any attacks (and also matches existing implementations better).
Fixes #110.
***
[Preview](https://encoding.spec.whatwg.org/branch-snapshots/annevk/gb18030-fourth-byte/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/encoding/378393f...951c471.html)
> gb18030 decoder: unwind from fourth byte when it's not a digit

- .travis.yml
- deploy.sh
This restores 9ce8d47 but refines such that if curl hits a timeout, it
will automatically retry each request up to 7 times.
From the curl(1) man page:
> --retry <num>
>    If  a  transient  error is returned when curl tries to perform a
>    transfer, it will retry this number of times before  giving  up.
>    Setting  the  number to 0 makes curl do no retries (which is the
>    default). Transient error means either: a timeout,  an  FTP  4xx
>    response code or an HTTP 5xx response code.
>
>    When  curl  is about to retry a transfer, it will first wait one
>    second and then for all forthcoming retries it will  double  the
>    waiting  time until it reaches 10 minutes which then will be the
>    delay between the rest of the retries.
Addresses #97
*** …
> Meta: retry HTML checker by curl, suppress warnings

- encoding.bs
- encodings.json
Fixes #70.
***
[Preview](https://encoding.spec.whatwg.org/branch-snapshots/replacement/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/encoding/eedd518...25d58aa.html)
> Add "replacement" as label for the replacement encoding

- encoding.bs
Whether something is simple or obvious is for the reader to determine.
***
[Preview](https://encoding.spec.whatwg.org/branch-snapshots/annevk/wording-nits/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/encoding/ee357f3...6bc288b.html)
> Editorial: wording nits

- encoding.bs
(Even thought it's not explicitly referenced.)
***
<a href="https://whatpr.org/encoding/124.html" title="Last updated on Apr 25, 2018, 9:10 AM GMT (ba65a05)">Preview</a> | <a href="https://whatpr.org/encoding/124/d55cb85...ba65a05.html" title="Last updated on Apr 25, 2018, 9:10 AM GMT (ba65a05)">Diff</a>
> Meta: TF-8 decode without BOM or fail is used at least once

- visualize.py
Currently, the character whose pointer is zero shows up as unassigned in the BMP coverage visualizations. Let's fix that.
> Include the character whose pointer is zero in BMP coverage visualizations

- encoding.bs
Fixes #87.
***
<a href="https://whatpr.org/encoding/136.html" title="Last updated on Apr 25, 2018, 12:05 PM GMT (b4e5aad)">Preview</a> | <a href="https://whatpr.org/encoding/136/9c80222...b4e5aad.html" title="Last updated on Apr 25, 2018, 12:05 PM GMT (b4e5aad)">Diff</a>
> Be clearer on which user agents the API applies to

- encoding.bs
Seems useful to explain the difference between concepts here and in Unicode.
***
<a href="https://whatpr.org/encoding/151.html" title="Last updated on Aug 23, 2018, 1:38 PM GMT (433e152)">Preview</a> | <a href="https://whatpr.org/encoding/151/19af047...433e152.html" title="Last updated on Aug 23, 2018, 1:38 PM GMT (433e152)">Diff</a>
> Add an informative note about the relationship of encodings and Unicode encoding schemes

- encoding.bs
Fixes #125.
***
<a href="https://whatpr.org/encoding/137.html" title="Last updated on Apr 25, 2018, 12:23 PM GMT (8a331a4)">Preview</a> | <a href="https://whatpr.org/encoding/137/9c80222...8a331a4.html" title="Last updated on Apr 25, 2018, 12:23 PM GMT (8a331a4)">Diff</a>
> Give clearer advice on hooks for standards

- encoding.bs
Due to an oversight in #111 the gb18030 decoder didn't always reset state before returning after a four-byte sequence.
Fixes #146.
***
<a href="https://whatpr.org/encoding/153.html" title="Last updated on Aug 30, 2018, 10:01 AM GMT (038dac4)">Preview</a> | <a href="https://whatpr.org/encoding/153/1c6f66a...038dac4.html" title="Last updated on Aug 30, 2018, 10:01 AM GMT (038dac4)">Diff</a>
> gb18030 decoder: unset state before returning

- encoding.bs
At this point it does not seem worth it to require further implementation changes and risk compatibility issues, so instead document the quirk.
Closes #115.
***
<a href="https://whatpr.org/encoding/155.html" title="Last updated on Sep 2, 2018, 9:31 AM GMT (9efea42)">Preview</a> | <a href="https://whatpr.org/encoding/155/b579018...9efea42.html" title="Last updated on Sep 2, 2018, 9:31 AM GMT (9efea42)">Diff</a>
> ISO-2022-JP encoder: document an oddity

- .htmlcheckerfilter
- Makefile
This change adds an `.htmlcheckerfilter` file containing regular-expression patterns that causes some particular warnings to be suppressed when the https://github.com/whatwg/whatwg.org/blob/master/resources.whatwg.org/build/deploy.sh script invokes the HTML checker on the Encoding build output.
The particular warnings that get suppressed are:
* Text run is not in Unicode Normalization Form C.
* Document uses the Unicode Private Use Area(s), which should not be used in publicly exchanged documents. (Charmod C073)
Otherwise, without this change, deployment of the Encoding spec will fail, because the https://github.com/whatwg/whatwg.org/blob/master/resources.whatwg.org/build/deploy.sh script causes the HTML checker to be invoked with the --Werror argument, which causes warnings to be treated …
> Suppress bad-Unicode HTML checker warnings

- encoding.bs
See https://github.com/heycam/webidl/pull/750.
***
<a href="https://whatpr.org/encoding/181.html" title="Last updated on Aug 9, 2019, 8:29 AM UTC (42efee1)">Preview</a> | <a href="https://whatpr.org/encoding/181/b4ff31c...42efee1.html" title="Last updated on Aug 9, 2019, 8:29 AM UTC (42efee1)">Diff</a>
> Align with IDL dictionary changes

- encoding.bs
This change changes some of the previous occurrences of the term "code point" for "scalar value", since it might not be clear to passing readers that output streams from decoding and input streams to encoding cannot contain tokens which are surrogate code points.
I haven't replaced the term "code point" in the indices section or in the handlers for the different encodings because those sections are heavy on numerical operations on code points, which aren't necessarily well-defined on scalar values. But perhaps the switch in terminology is more confusing than replacing the term throughout.
Fixes #195.
***
<a href="https://whatpr.org/encoding/196.html" title="Last updated on Jan 20, 2020, 1:19 PM UTC (bd1331c)">Preview</a> | <a href="https://whatpr.org/encoding/196/b818a7f...bd1331c.html" …
> Clarify that encoding tokens are scalar values.

- visualize.py
As a frequent user of the visualizations, I've come to the conclusion that, for practical purposes, I always need to look up byte values rather than index offsets in the single-byte visualizations. This changes the row labels for the single-byte visualizations to use byte values.
> Label single-byte visualization rows by byte value

- encoding.bs
This change moves the BOM splitting part of the decode hook into a separate hook which does not consume any bytes of the token stream.
This will allow fixing a long-standing issue in the HTML encoding sniffing algorithm with the document's character encoding being set to the wrong result when there is a BOM (see whatwg/html#1077).
Closes #128.
***
<a href="https://whatpr.org/encoding/203.html" title="Last updated on Mar 24, 2020, 8:24 AM UTC (ed1ec60)">Preview</a> | <a href="https://whatpr.org/encoding/203/64e63cc...ed1ec60.html" title="Last updated on Mar 24, 2020, 8:24 AM UTC (ed1ec60)">Diff</a>
> Add a BOM sniffing hook for better integration with HTML

- encoding.bs
- encodings.json
Blink and WebKit have supported these for a long time.
Tests: https://github.com/web-platform-tests/wpt/pull/23427.
Fixes #168.
* Presumably Chrome/Safari
* Firefox
* See above.
* Chrome: N/A
* Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1635779
* Safari: N/A
(See [WHATWG Working Mode: Changes](https://whatwg.org/working-mode#changes) for more details.)
***
<a href="https://whatpr.org/encoding/211.html" title="Last updated on May 6, 2020, 2:22 PM UTC (a39de01)">Preview</a> | <a href="https://whatpr.org/encoding/211/3911f81...a39de01.html" title="Last updated on May 6, 2020, 2:22 PM UTC (a39de01)">Diff</a>
> Add more UTF-8, UTF-16BE, and UTF-16LE labels

- encoding.bs
This was left over from #175.
***
<a href="https://whatpr.org/encoding/216.html" title="Last updated on May 29, 2020, 2:05 PM UTC (893f58b)">Preview</a> | <a href="https://whatpr.org/encoding/216/dd8e302...893f58b.html" title="Last updated on May 29, 2020, 2:05 PM UTC (893f58b)">Diff</a>
> Editorial: remove a lone close parenthesis

- encoding.bs
***
<a href="https://whatpr.org/encoding/226.html" title="Last updated on Sep 1, 2020, 9:02 AM UTC (b248d83)">Preview</a> | <a href="https://whatpr.org/encoding/226/81329ae...b248d83.html" title="Last updated on Sep 1, 2020, 9:02 AM UTC (b248d83)">Diff</a>
> Meta: “UTF-8 or death”

- encoding.bs
***
<a href="https://whatpr.org/encoding/228.html" title="Last updated on Sep 8, 2020, 1:38 PM UTC (f3bf4e0)">Preview</a> | <a href="https://whatpr.org/encoding/228/46711e6...f3bf4e0.html" title="Last updated on Sep 8, 2020, 1:38 PM UTC (f3bf4e0)">Diff</a>
> Editorial: add a common term for UTF-16BE and UTF-16LE

- encoding.bs
See https://github.com/whatwg/encoding/pull/215#issuecomment-690023201
***
<a href="https://whatpr.org/encoding/229.html" title="Last updated on Sep 10, 2020, 7:01 AM UTC (1d07883)">Preview</a> | <a href="https://whatpr.org/encoding/229/4d43132...1d07883.html" title="Last updated on Sep 10, 2020, 7:01 AM UTC (1d07883)">Diff</a>
> Editorial: Fix the type of the output argument to encode / UTF-8 encode

- encoding.bs
Follows https://github.com/whatwg/streams/pull/1073.
***
<a href="https://whatpr.org/encoding/224.html" title="Last updated on Sep 15, 2020, 8:36 AM UTC (7bfd7db)">Preview</a> | <a href="https://whatpr.org/encoding/224/46711e6...7bfd7db.html" title="Last updated on Sep 15, 2020, 8:36 AM UTC (7bfd7db)">Diff</a>
> Use new Streams algorithm and mixins

- encoding.bs
An "output" parameter was added to the hooks for standards in whatwg/encoding#215, but no explanation was given as to why it was needed. This change adds that clarification.
***
<a href="https://whatpr.org/encoding/230.html" title="Last updated on Sep 21, 2020, 10:09 AM UTC (eade6ff)">Preview</a> | <a href="https://whatpr.org/encoding/230/0ca7c4e...eade6ff.html" title="Last updated on Sep 21, 2020, 10:09 AM UTC (eade6ff)">Diff</a>
> Clarify the usage the output I/O queues in the hooks

- tools-clean.py
The previous `raise "Duplicate label:", label` used in earlier revisions of this script would have worked up to and including Python 2.5, since exception types could be strings (with the exception message kept around separately) for legacy reasons, since class-based exceptions were only added in Python 1.5 (in 1997); i.e. `"Duplicate label:` would still be accepted as an exception type (although the colon would be redundant to the one inserted between the exception type and value in the traceback).
This ability was removed in Python 2.6. The use of something like `raise ValueError, ("Duplicate label: %r" % label)` would have been okay up to and including Python 2.7; however, due to the removal of string exception types, the syntax for passing the class and value (as opposed to passing an …
> Minor correction to a tool script: raise does not work like print

- encoding.bs
This way you can invoke its handler directly without going the process algorithm as is needed to fix #235. This also avoids the need for "prepend" in the "process" algorithm.
Additionally, this commit adds two clarifying asserts to the "process" algorithm documenting what error modes can be in effect when.
***
<a href="https://whatpr.org/encoding/236.html" title="Last updated on Oct 20, 2020, 12:55 PM UTC (2c07038)">Preview</a> | <a href="https://whatpr.org/encoding/236/92569b5...2c07038.html" title="Last updated on Oct 20, 2020, 12:55 PM UTC (2c07038)">Diff</a>
> Editorial: make ISO-2022-JP encoder perform error state switch

- encoding.bs
@andreubotella would appreciate your thoughts on this as well. I wanted to split this section into two given that I need two new algorithms for the URL standard (get an encoder and encode or fail) that both are somewhat wonky and probably need a bit of explanation and it seems bad to explain that together with all the UTF-8-centric primitives everyone ought to be using.
***
<a href="https://whatpr.org/encoding/237.html" title="Last updated on Oct 22, 2020, 9:15 AM UTC (789436e)">Preview</a> | <a href="https://whatpr.org/encoding/237/a5e3e11...789436e.html" title="Last updated on Oct 22, 2020, 9:15 AM UTC (789436e)">Diff</a>
> Reorganize hooks for standards

- encoding.bs
Please excuse the branch name. The first commit is #237 and I will rebase this once @andreubotella has looked at that.
I suspect some changes might be needed here around my IO queue usage. In particular, in this scenario we probably do want to push end-of-queue upon encountering an error, to make conversion to bytes easier for the caller.
***
<a href="https://whatpr.org/encoding/238.html" title="Last updated on Oct 23, 2020, 11:53 AM UTC (4632a05)">Preview</a> | <a href="https://whatpr.org/encoding/238/cfc443e...4632a05.html" title="Last updated on Oct 23, 2020, 11:53 AM UTC (4632a05)">Diff</a>
> Add get an encoder and encode or fail for URLs

- encoding.bs
And also stop defaulting error mode in "run" and "process".
Fixes #240.
r? @andreubotella
***
<a href="https://whatpr.org/encoding/241.html" title="Last updated on Oct 26, 2020, 4:38 PM UTC (abf398c)">Preview</a> | <a href="https://whatpr.org/encoding/241/c55584b...abf398c.html" title="Last updated on Oct 26, 2020, 4:38 PM UTC (abf398c)">Diff</a>
> Clarify instance language around decoders and encoders

- encoding.bs
"Run" is now "process a queue" and "process" is now "process an item".
Also tidy up the error mode note and shorten the "process an item" algorithm.
Closes #245.
***
<a href="https://whatpr.org/encoding/246.html" title="Last updated on Nov 2, 2020, 3:38 PM UTC (ec6d39e)">Preview</a> | <a href="https://whatpr.org/encoding/246/0bea013...ec6d39e.html" title="Last updated on Nov 2, 2020, 3:38 PM UTC (ec6d39e)">Diff</a>
> Editorial: rename internal run algorithm

- encoding.bs
Closes #253.
***
<a href="https://whatpr.org/encoding/254.html" title="Last updated on Feb 26, 2021, 11:19 AM UTC (394c83a)">Preview</a> | <a href="https://whatpr.org/encoding/254/4d54adc...394c83a.html" title="Last updated on Feb 26, 2021, 11:19 AM UTC (394c83a)">Diff</a>
> Document gb18030 decoder end-of-queue oddity

- .htmlcheckerfilter
- encoding.bs
Follows whatwg/streams#1110.
I just noticed that the Encoding standard was failing to build because of these changes to the Streams standards.
***
<a href="https://whatpr.org/encoding/260.html" title="Last updated on Jun 21, 2021, 8:56 AM UTC (cb41266)">Preview</a> | <a href="https://whatpr.org/encoding/260/75b988c...cb41266.html" title="Last updated on Jun 21, 2021, 8:56 AM UTC (cb41266)">Diff</a>
> Editorial: Use "set up" for TransformStreams rather than "create"

- encoding.bs
At various times in the ISO-2022-JP decoder and encoder, the prepend operation was being called with an end-of-queue item, even though that was made illegal in #215. This change removes those instances, in order to keep the same behavior as before #215.
This was discovered in #263.
***
<a href="https://whatpr.org/encoding/266.html" title="Last updated on Jun 21, 2021, 11:03 AM UTC (caf80f5)">Preview</a> | <a href="https://whatpr.org/encoding/266/395efaf...caf80f5.html" title="Last updated on Jun 21, 2021, 11:03 AM UTC (caf80f5)">Diff</a>
> Editorial: Fix instances of prepend used with an end-of-queue item

- encoding.bs
This change fixes `TextDecoderStream`'s "flush and enqueue" algorithm to handle the end of the stream in the same way as a call to `TextDecoder`'s `decode` method with no parameters.
Fixes #263.
* Firefox and Safari implement this.
* Chrome has bugs around end-of-stream handling, but they are shared with `TextDecoder`'s non-streaming mode.
* …
* Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=978522
* Firefox: N/A
* Safari: N/A
(See [WHATWG Working Mode: Changes](https://whatwg.org/working-mode#changes) for more details.)
***
<a href="https://whatpr.org/encoding/265.html" title="Last updated on Jun 21, 2021, 11:04 AM UTC (ed72ecb)">Preview</a> | <a href="https://whatpr.org/encoding/265/395efaf...ed72ecb.html" title="Last updated on Jun 21, 2021, 11:04 AM UTC …
> Fix TextDecoderStream's behavior when processing the end of stream

- encoding.bs
Follows https://github.com/heycam/webidl/pull/987.
***
<a href="https://whatpr.org/encoding/262.html" title="Last updated on Sep 27, 2021, 1:25 PM UTC (ad400cd)">Preview</a> | <a href="https://whatpr.org/encoding/262/b74cc91...ad400cd.html" title="Last updated on Sep 27, 2021, 1:25 PM UTC (ad400cd)">Diff</a>
> Editorial: use new Web IDL primitives for Uint8Array writing

- review-drafts/2023-06.bs
The [June 2023 Review Draft](https://encoding.spec.whatwg.org/review-drafts/2023-06/) for this Workstream will be published shortly after merging this pull request.
Under the [WHATWG IPR Policy](https://whatwg.org/ipr-policy), Participants may, within 45 days after publication of a Review Draft, exclude certain Essential Patent Claims from the Review Draft Licensing Obligations. See the [IPR Policy](https://whatwg.org/ipr-policy) for details.
***
<a href="https://whatpr.org/encoding/314.html" title="Last updated on Jun 19, 2023, 9:04 AM UTC (265babb)">Preview</a> | <a href="https://whatpr.org/encoding/314/2819334...265babb.html" title="Last updated on Jun 19, 2023, 9:04 AM UTC (265babb)">Diff</a>
> Review Draft Publication: June 2023

- encoding.bs
Fixes #325 and closes #326.
***
<a href="https://whatpr.org/encoding/328.html" title="Last updated on Mar 13, 2024, 8:52 AM UTC (49ea500)">Preview</a> | <a href="https://whatpr.org/encoding/328/b53fc98...49ea500.html" title="Last updated on Mar 13, 2024, 8:52 AM UTC (49ea500)">Diff</a>
> Editorial: make prepend more clearly operate on a list

- encoding.bs
Fixes #329.
***
<a href="https://whatpr.org/encoding/330.html" title="Last updated on Jun 13, 2024, 2:17 PM UTC (38eb3a2)">Preview</a> | <a href="https://whatpr.org/encoding/330/239008d...38eb3a2.html" title="Last updated on Jun 13, 2024, 2:17 PM UTC (38eb3a2)">Diff</a>
> Editorial: correct "is empty" reference

- encoding.bs
Also introduce an operation to obtain a scalar value from surrogates.
Eventually the lead/trail byte stuff needs to be made consistent with this as well.
***
<a href="https://whatpr.org/encoding/309.html" title="Last updated on Oct 4, 2024, 9:30 AM UTC (8a5f3b0)">Preview</a> | <a href="https://whatpr.org/encoding/309/2c3853e...8a5f3b0.html" title="Last updated on Oct 4, 2024, 9:30 AM UTC (8a5f3b0)">Diff</a>
> Editorial: use leading and trailing surrogate

- .htmlcheckerfilter
- visualize.py
> Meta: use aria-description instead of aria-label

- encoding.bs
***
<a href="https://whatpr.org/encoding/346.html" title="Last updated on Apr 22, 2025, 2:50 PM UTC (adc8d46)">Preview</a> | <a href="https://whatpr.org/encoding/346/9477a2e...adc8d46.html" title="Last updated on Apr 22, 2025, 2:50 PM UTC (adc8d46)">Diff</a>
> Meta: add <div algorithm> everywhere except for the encoding handlers

- encoding.bs
And restore a newline I removed in the prior commit.
***
<a href="https://whatpr.org/encoding/347.html" title="Last updated on Apr 22, 2025, 3:35 PM UTC (a1e36c3)">Preview</a> | <a href="https://whatpr.org/encoding/347/00ef38e...a1e36c3.html" title="Last updated on Apr 22, 2025, 3:35 PM UTC (a1e36c3)">Diff</a>
> Meta: add algorithm attribute to encoding sections

- encoding.bs
Make several improvements:
- Stop using "then" before nested steps.
- Start using "then" after an if conditional.
- Use camel case for variables (codeUnit, not code unit).
- Stop manipulating state and initializing variables in a conditional for nested steps.
(More needs to be done, but this also needs to be reviewable.)
***
<a href="https://whatpr.org/encoding/348.html" title="Last updated on Apr 23, 2025, 7:31 AM UTC (4d5f14f)">Preview</a> | <a href="https://whatpr.org/encoding/348/317401a...4d5f14f.html" title="Last updated on Apr 23, 2025, 7:31 AM UTC (4d5f14f)">Diff</a>
> Editorial: align with Infra

- encoding.bs
- tools-label-table.py
***
<a href="https://whatpr.org/encoding/345.html" title="Last updated on Apr 17, 2025, 7:59 AM UTC (cf74334)">Preview</a> | <a href="https://whatpr.org/encoding/345/9477a2e...cf74334.html" title="Last updated on Apr 17, 2025, 7:59 AM UTC (cf74334)">Diff</a>
> Explain the relationship between windows-1252, Latin1, and ASCII

- encoding.bs
In particular:
- Follow more code points with their representation.
- Rename lead and trail to leading and trailing.
- Define the types of concept members.
- More "then" following "If".
This fixes #242 and fixes #304.
***
<a href="https://whatpr.org/encoding/349.html" title="Last updated on Apr 24, 2025, 7:19 AM UTC (f1dc0d3)">Preview</a> | <a href="https://whatpr.org/encoding/349/36fb4e7...f1dc0d3.html" title="Last updated on Apr 24, 2025, 7:19 AM UTC (f1dc0d3)">Diff</a>
> Editorial: align even more with Infra

- encoding.bs
Also address a couple additional Infra nits I noticed along the way.
Fixes #150 (finally) and helps with #334.
***
<a href="https://whatpr.org/encoding/350.html" title="Last updated on Apr 24, 2025, 8:22 AM UTC (561c333)">Preview</a> | <a href="https://whatpr.org/encoding/350/36fb4e7...561c333.html" title="Last updated on Apr 24, 2025, 8:22 AM UTC (561c333)">Diff</a>
> Properly create Uint8Array objects

- review-drafts/2025-06.bs
The [June 2025 Review Draft](https://encoding.spec.whatwg.org/review-drafts/2025-06/) for this Workstream will be published shortly after merging this pull request.
Under the [WHATWG IPR Policy](https://whatwg.org/ipr-policy), Participants may, within 45 days after publication of a Review Draft, exclude certain Essential Patent Claims from the Review Draft Licensing Obligations. See the [IPR Policy](https://whatwg.org/ipr-policy) for details.
***
<a href="https://whatpr.org/encoding/352.html" title="Last updated on Jun 16, 2025, 7:33 AM UTC (9563f9b)">Preview</a> | <a href="https://whatpr.org/encoding/352/2f2e812...9563f9b.html" title="Last updated on Jun 16, 2025, 7:33 AM UTC (9563f9b)">Diff</a>
> Review Draft Publication: June 2025
