Overview.html
Overview.src.html

Caused by 19a25b5fcae895853d964b7ee6afa2fe9b6070a8. Fixes #42.

Fix regression in utf-8 decoder

---

Overview.src.html

Editorial: avoid upsetting lazy compilers

---

Overview.html
Overview.src.html

Editorial: make gb18030 math more clear

---

encoding.bs
encoding.html

Editorial: cross-reference more IDL terms

---

encoding.bs

Editorial: fix formatting of code and add new to constructor

---

.editorconfig
.gitattributes
.pr-preview.json
README.md
encoding.bs

See https://github.com/whatwg/meta/issues/16.

Meta: enable PR preview

---

encoding.bs

***
[Preview](https://encoding.spec.whatwg.org/branch-snapshots/annevk/implementation-considerations/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/encoding/ee2bd34...279eac3.html)

Document an implementation buffer trick

---

encoding.bs

***
[Preview](https://encoding.spec.whatwg.org/branch-snapshots/annevk/indexing/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/encoding/ee2bd34...ec3829c.html)

Editorial: enable indexes and fix a couple minor nits

---

encoding.bs

***
[Preview](https://encoding.spec.whatwg.org/branch-snapshots/annevk/editorial/) | [Diff](https://s3.amazonaws.com/pr-preview/whatwg/encoding/9ce8d47...fcf3484.html)

Editorial: ensure various bits link properly

---

tools-index.py

Meta: use HTTPS rather than FTP for UnicodeData.txt

---

encoding.bs

***
<a href="https://whatpr.org/encoding/152.html" title="Last updated on Aug 29, 2018, 10:50 AM GMT (f188fec)">Preview</a> | <a href="https://whatpr.org/encoding/152/c3e3887...f188fec.html" title="Last updated on Aug 29, 2018, 10:50 AM GMT (f188fec)">Diff</a>

Meta: fix Bikeshed link error

---

encoding.bs

Fixes #176.
***
<a href="https://whatpr.org/encoding/198.html" title="Last updated on Mar 2, 2020, 6:17 PM UTC (0f9aac0)">Preview</a> | <a href="https://whatpr.org/encoding/198/673e65a...0f9aac0.html" title="Last updated on Mar 2, 2020, 6:17 PM UTC (0f9aac0)">Diff</a>

Editorial: change the remaining flags to booleans

---

encoding.bs

See https://github.com/whatwg/infra/pull/292.
(This needs to wait at least a day until after that PR is merged as otherwise the cross-references might go faulty.)
cc @andreubotella
***
<a href="https://whatpr.org/encoding/199.html" title="Last updated on Mar 11, 2020, 10:15 AM UTC (0f00880)">Preview</a> | <a href="https://whatpr.org/encoding/199/64e63cc...0f00880.html" title="Last updated on Mar 11, 2020, 10:15 AM UTC (0f00880)">Diff</a>

Editorial: align with Infra string changes

---

encoding.bs

Add a note documenting some things mention in #207.
***
<a href="https://whatpr.org/encoding/209.html" title="Last updated on May 6, 2020, 11:41 AM UTC (f204869)">Preview</a> | <a href="https://whatpr.org/encoding/209/037500e...f204869.html" title="Last updated on May 6, 2020, 11:41 AM UTC (f204869)">Diff</a>

Add a non-normative note about how the set of encodings was selected

---

encoding.bs

And cleanup various other editorial patterns.
***
<a href="https://whatpr.org/encoding/175.html" title="Last updated on May 13, 2020, 4:30 AM UTC (d1af7ea)">Preview</a> | <a href="https://whatpr.org/encoding/175/b991dea...d1af7ea.html" title="Last updated on May 13, 2020, 4:30 AM UTC (d1af7ea)">Diff</a>

Editorial: use IDL's this and adopt more Infra

---

encoding.bs

Closes #154.
***
<a href="https://whatpr.org/encoding/213.html" title="Last updated on May 14, 2020, 4:38 AM UTC (9fdb861)">Preview</a> | <a href="https://whatpr.org/encoding/213/5c571e9...9fdb861.html" title="Last updated on May 14, 2020, 4:38 AM UTC (9fdb861)">Diff</a>

Editorial: introduce continue to serialize stream

---

.htmlcheckerfilter
encoding.bs

Fixes #212.
***
<a href="https://whatpr.org/encoding/214.html" title="Last updated on May 14, 2020, 4:53 AM UTC (d070105)">Preview</a> | <a href="https://whatpr.org/encoding/214/650ea5a...d070105.html" title="Last updated on May 14, 2020, 4:53 AM UTC (d070105)">Diff</a>

Editorial: consolidate shared state

---

visualize.py

Not entirely sure how I stumbled upon this, but I checked if this was still relevant and it's not so I decided to patch it. It didn't seem appreciably faster or slower either, though I didn't do detailed measurements.

Meta: cleanup visualize.py

---

encoding.bs

***
<a href="https://whatpr.org/encoding/232.html" title="Last updated on Sep 29, 2020, 2:44 PM UTC (9162b61)">Preview</a> | <a href="https://whatpr.org/encoding/232/3e16fb3...9162b61.html" title="Last updated on Sep 29, 2020, 2:44 PM UTC (9162b61)">Diff</a>

Meta: link Review Draft

---

encoding.bs

Closes #239, closes #243.
cc @wlammen
***
<a href="https://whatpr.org/encoding/244.html" title="Last updated on Oct 26, 2020, 11:06 AM UTC (638d76a)">Preview</a> | <a href="https://whatpr.org/encoding/244/c55584b...638d76a.html" title="Last updated on Oct 26, 2020, 11:06 AM UTC (638d76a)">Diff</a>

Add some minor clarifications.

---

encoding.bs

Ref: tc39/proposal-shadowrealm#331
* Positive initial signals from Google, Apple, Mozilla on the general direction.
* …
* Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1281880
* Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1747059
* Safari: https://bugs.webkit.org/show_bug.cgi?id=234554
(See [WHATWG Working Mode: Changes](https://whatwg.org/working-mode#changes) for more details.)
***
<a href="https://whatpr.org/encoding/274.html" title="Last updated on Oct 19, 2021, 3:42 PM UTC (0698a4d)">Preview</a> | <a href="https://whatpr.org/encoding/274/be33374...0698a4d.html" title="Last updated on Oct 19, 2021, 3:42 PM UTC (0698a4d)">Diff</a>
***
<a href="https://whatpr.org/encoding/274.html" title="Last updated on Dec 21, 2021, 1:47 PM UTC (0698a4d)">Preview</a> | <a …

Expose everywhere

---

encoding.bs

***
<a href="https://whatpr.org/encoding/299.html" title="Last updated on Oct 26, 2022, 12:15 PM UTC (c5b0c0a)">Preview</a> | <a href="https://whatpr.org/encoding/299/67e3665...c5b0c0a.html" title="Last updated on Oct 26, 2022, 12:15 PM UTC (c5b0c0a)">Diff</a>

Meta: my employer changed

---

encoding.bs

See https://github.com/whatwg/webidl/pull/1311 for context.
***
<a href="https://whatpr.org/encoding/313.html" title="Last updated on Jun 15, 2023, 4:43 PM UTC (940c7ca)">Preview</a> | <a href="https://whatpr.org/encoding/313/3721bec...940c7ca.html" title="Last updated on Jun 15, 2023, 4:43 PM UTC (940c7ca)">Diff</a>

Editorial: account for SharedArrayBuffer change in Web IDL

---

encoding.bs

***
<a href="https://whatpr.org/encoding/353.html" title="Last updated on Jul 16, 2025, 12:28 PM UTC (208a5a8)">Preview</a> | <a href="https://whatpr.org/encoding/353/67494fc...208a5a8.html" title="Last updated on Jul 16, 2025, 12:28 PM UTC (208a5a8)">Diff</a>

Meta: link Simplified Chinese translation

---

encoding.bs

***
<a href="https://whatpr.org/encoding/354.html" title="Last updated on Aug 12, 2025, 1:14 PM UTC (0cbe5e9)">Preview</a> | <a href="https://whatpr.org/encoding/354/74ac36f...0cbe5e9.html" title="Last updated on Aug 12, 2025, 1:14 PM UTC (0cbe5e9)">Diff</a>

Meta: link to Korean translations
